### ISSUE TITLE
repository empty

### ISSUE THREAD

**Issue by el-smeagel** [sharkiller/ptxt4manager#1]
Hello Sharkiller, I´m making czech translation SH - Awakened Remastered, I can´t figure out how to make quizz (choiceset) keymap work. I´m using bacter tools in which I can´t edit those params. So I found out you made this ptxt4manager. But this repository is empty.
Could you please help me somehow?

**Comment by sharkiller** [comment]
@el-smeagel hey I uploaded the code. Is old and not clean. 

You can see an example of how to use it here: 
https://github.com/sharkiller/ptxt4manager/blob/main/ptxt4_manager/example.php

Also on the scripts folder you can see examples of how to generate correct glyphs or quizz to replace on the unpacked ptxt4. 
https://github.com/sharkiller/ptxt4manager/tree/main/scripts  

this project require a php server or executable to use. maybe some dependencies like xdebug can be removed if you dont have it. but was an old project.

**Comment by sharkiller** [comment]
Also upload the pak manager. that is better than bacter tools because it doesnt ignore files or structure used by lips files or audio.

**Comment by el-smeagel** [comment]
Wow, thank you very much.
I´m really grateful for provided files and examples how to use it. I really appreciate it.

To be true, I´ve already lost hope, but you´ve responded. 
One more time, thanks.

Have a good day ;)
